### ISSUE TITLE
Screen position and resolution is incorrect

### ISSUE THREAD

**Issue by DrBox** [HelloKS/MaiMai-VR#4]
Sorry for the low quality image, but basically the maimai finale screen is big and position inside the center of the two cabinet, like in this image, I have no idea how to fix this. Any help please?
![215887213_320336589792065_7824930172809715516_n](https://user-images.githubusercontent.com/20185388/126322779-c17debbf-2290-41fa-b130-8fb052219dd4.jpg)

**Comment by HelloKS** [comment]
Hello, sorry for delay. somehow I turned off notifications. :(

I think you enabled 1P only mode and this fork doesn't work if it is.
Please set `1P_ONLY` to  `0`.
