### ISSUE TITLE
Support Maimai Sp?

### ISSUE THREAD

**Issue by xiaopeng12138** [HelloKS/MaiMai-VR#5]
So, Maimai Sp is now leaked. Maybe this can support it in the Future? I think it is not hard because Maimai Sp support xinput.

**Comment by HelloKS** [comment]
Hello,

Long story short, Yes. I'm aware of it and working on it.
Current blocking issues are:

- I'm still finding a good way to implement screen touch, as DX charts are heavily using it.
- I'm also working on DX cab models because running DX variant on old cab model is kinda... weird.

I can't make any ETA now but it will eventually done.

**Comment by xiaopeng12138** [comment]
> 你好，
> 
> 长话短说，是的。我知道并正在努力。
> 当前的阻塞问题是：
> 
> * 我仍在寻找实现屏幕触摸的好方法，因为 DX 图表正在大量使用它。
> * 我也在研究 DX cab 模型，因为在旧的 cab 模型上运行 DX 变体有点......奇怪。
> 
> 我现在无法进行任何预计到达时间，但最终会完成。

WOW, Thank you and your hard work so much. I will wait it!

**Comment by HelloKS** [comment]
Thanks.
Please let's keep open this thread for project issue tracking until complete. :)

**Comment by renji24ip** [comment]
I use google translate
maimaiSplash can directly use the touch screen

**Comment by xiaopeng12138** [comment]
> 我用google translate
> maimaiSplash 可以直接用触摸屏

yes, it supports touchscreen but it's not very good because of the way windows handle touch. sp use comport 3 and comport 4 to communicate with touch screen. the protocol can be found in main programms dll (because it uses unity so it's quite easy to decompile.(but my coding skill is shit so idk how to do this. (btw the led is very hard to hook because one dll is upset.

**Comment by xiaopeng12138** [comment]
So, I tried to use this touch injection package:
https://github.com/hecomi/uTouchInjection
It works, but the delay is huge when I try to inject 34 input points. Now I'm trying to use com0com to create a virtual com port for maimai but my c# skill is very bad so...XD it will take some time. XD
and here is the touch collision model I made using blender, you can freely use it
[SPTOUCH.zip](https://github.com/HelloKS/MaiMai-VR/files/7488949/SPTOUCH.zip)

NEW UPDATE: I already did it! now it support touch input via serial. I used this library:https://github.com/Sucareto/Mai2Touch
but it needs some fix. the collision object is still to complex and it only support oculus quest 2 (because I use oculus link and id want pass the data to steamvr then back to headset. )
i will make a fork after I clean up my code. so, coming soon XD

**Comment by xiaopeng12138** [comment]
NEWNEW UPDAT: Here is the pre-build version of maimai vr sp:
https://drive.google.com/file/d/1WSbj26NrMCVkMxp_IdR9tOjLJfB2tO0K/view?usp=sharing
Password is: NOTSEGA
**!!ONLY SUPPORT OCULUS LINK!!** It May support Quest 1 controller but the hitbox is made for Quest 2 controller.
because my coding skill is shit so I will post source code in the future when I'm ready. I need to tidy up my code.

Install com0com: https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/powersdr-iq/setup_com0com_W7_x64_signed.exe (the official source forget has no windows driver signature. This version is pre signed)
Bind serial port 3 to 5 (COM3 and COM5)
Start maimai first, then start maimaivr, then goto maintenance mod in your maimai then exit maintenance mod(reconfigure touch panel).
You need to set **DummyTouchPanel=1 to 0** in mai2.ini then run maimai in window mod by modifiy the start.bat file. this is my setting: Sinmai.exe -screen-fullscreen 0 -screen-width 1170 -screen-height 1050.
(sry for my bad English)

**Comment by HelloKS** [comment]
Sorry for long silence. Due to my real life situation, I don't have enough time since then and this issue was "on hold" status.
Since I don't have any estimation nor promises now, someone who have interest in this might want to check out author's fork.
Thank you for letting me know about this. You could keep this issue open or close at your will.

**Comment by xiaopeng12138** [comment]
> Sorry for long silence. Due to my real life situation, I don't have enough time since then and this issue was "on hold" status. Since I don't have any estimation nor promises now, someone who have interest in this might want to check out author's fork. Thank you for letting me know about this. You could keep this issue open or close at your will.

I will keep this issue until I clean up my code and public it. But I still have to thank you for your work

**Comment by xiaopeng12138** [comment]
https://github.com/xiaopeng12138/MaiMai-VR
I uploaded it so now I'm gonna close this issue now.
