### ISSUE TITLE
What is the correct resolution for best intended display?

### ISSUE THREAD

**Issue by Presidentsenpai** [HelloKS/MaiMai-VR#8]
Thank you so much for making this, I really love it. I am using 2 player display, and it aligns well but I was wondering, what is the expected resolution? Currently doing 1440 X 960 and my results are good but not perfect.

**Comment by HelloKS** [comment]
Hello,

Recommended ratio is 1:1, I personally test it with in 1000x1000. If you are using 1P mode, it won't work as expected so please disable it first.

Thanks.
